#!/bin/sh

# Verifica se o usuário do supervisor é root ou www-data
if [ "$SUPERVISOR_PHP_USER" != "root" ] && [ "$SUPERVISOR_PHP_USER" != "www-data" ]; then
    echo "You should set SUPERVISOR_PHP_USER to either 'www-data' or 'root'."
    exit 1
fi

# Cria /.composer se necessário (geralmente usado no builder, pode ser removido)
[ -d /.composer ] || mkdir /.composer
chmod -R ugo+rw /.composer

# Se argumentos foram passados ao container, executa diretamente
if [ "$#" -gt 0 ]; then
    if [ "$SUPERVISOR_PHP_USER" = "root" ]; then
        exec "$@"
    else
        exec su-exec www-data "$@"
    fi
else
     # 🔗 Garante o symlink do storage (storage:link)
    if [ ! -L /var/www/html/public/storage ]; then
        echo "🔗 Criando symlink: public/storage → storage/app/public"
        su-exec www-data php artisan storage:link
    fi
    # Garante que o diretório de upload do nginx exista
    if [ ! -d /var/lib/nginx/tmp/client_body ]; then
        echo "📁 Criando /var/lib/nginx/tmp/client_body"
        mkdir -p /var/lib/nginx/tmp/client_body
        chown -R www-data:www-data /var/lib/nginx
        chmod -R 700 /var/lib/nginx/tmp
    fi
    exec /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
fi
