services:
  app.siv:
    build:
      context: '..'
      dockerfile: 'production/.docker/Dockerfile.prod'
      args:
        WWWGROUP: '82'
        WWWUSER: '82'
    env_file:
      - .env
    depends_on:
      - redis
      - minio
    restart: unless-stopped
    volumes:
      - storage_data:/var/www/html/storage
    ports:
      - '${APP_PORT:-80}:80'
      - '${REVERB_PORT:-8080}:8080'
    environment:
      WWWUSER: '82'
      SUPERVISOR_PHP_USER: 'www-data'
      SUPERVISOR_PHP_GROUP: 'www-data'
      LARAVEL_SIV: 1
      IGNITION_LOCAL_SITES_PATH: '${PWD}'
    networks:
      - siv-network

  redis:
    image: redis:alpine
    container_name: redis_prod
    ports:
      - '${FORWARD_REDIS_PORT:-6379}:6379'
    volumes:
      - redis_data:/data
    networks:
      - siv-network
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      retries: 3
      timeout: 5s

  minio:
    image: minio/minio:latest
    container_name: minio_storage_prod
    restart: always
    env_file:
      - .env
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - '9000:9000'
      - '9001:9001'
    command: server --console-address ":9001" /data
    volumes:
      - minio_data:/data
    networks:
      - siv-network

volumes:
  storage_data:
    driver: local
  minio_data:
    driver: local
  redis_data:
    driver: local

networks:
  siv-network:
    driver: bridge
