#!/bin/sh

# Verifica se o usuário do supervisor é root ou www-data
if [ "$SUPERVISOR_PHP_USER" != "root" ] && [ "$SUPERVISOR_PHP_USER" != "www-data" ]; then
    echo "You should set SUPERVISOR_PHP_USER to either 'www-data' or 'root'."
    exit 1
fi

# Cria /.composer se necessário (geralmente usado no builder, pode ser removido)
[ -d /.composer ] || mkdir /.composer
chmod -R ugo+rw /.composer

# Se argumentos foram passados ao container, executa diretamente
if [ "$#" -gt 0 ]; then
    if [ "$SUPERVISOR_PHP_USER" = "root" ]; then
        exec "$@"
    else
        exec su-exec www-data "$@"
    fi
else
    exec /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
fi
