name: Deploy SIV to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build and Deploy to Production
    runs-on: self-hosted

    steps:
      - name: 📥 Checkout do repositório
        uses: actions/checkout@v4

      - name: 🧪 Liberar espaço em disco antes do build
        run: |
          docker system prune -af || true

      - name: 📄 Criar arquivo .env.production
        run: echo "${{ secrets.ENV_PRODUCTION_CONTENT }}" > .env.production

      - name: 🧼 Derrubar containers antigos
        run: docker compose -f docker-compose.prod.yml down --remove-orphans

      - name: 🛠️ Build do projeto Laravel + React
        run: docker compose -f docker-compose.prod.yml build --no-cache

      - name: 🚀 Subir containers em segundo plano
        run: docker compose -f docker-compose.prod.yml up -d

      - name: 🧩 Rodar comandos Laravel (migrate, cache)
        run: |
          docker compose -f docker-compose.prod.yml exec -T app.siv php artisan migrate --force
          docker compose -f docker-compose.prod.yml exec -T app.siv php artisan config:clear
          docker compose -f docker-compose.prod.yml exec -T app.siv php artisan config:cache
          docker compose -f docker-compose.prod.yml exec -T app.siv php artisan route:cache
          docker compose -f docker-compose.prod.yml exec -T app.siv php artisan view:cache

      - name: ✅ Notificação Telegram (sucesso)
        if: success()
        run: |
          TEXT=$(cat <<EOF
          ✅ *Deploy do SIV finalizado com sucesso!*
          *Branch:* \`main\`
          *Commit:* [${GITHUB_SHA}](${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/commit/${GITHUB_SHA})
          *Autor:* ${GITHUB_ACTOR}
          *Ambiente:* Produção
          *Data:* $(date -u)
          EOF
                    )
                    curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage \
                      -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
                      --data-urlencode text="$TEXT" \
                      -d parse_mode=Markdown

                - name: ❌ Notificação Telegram (erro)
                  if: failure()
                  run: |
                    TEXT=$(cat <<EOF
          ❌ *Erro no deploy do SIV!*
          *Branch:* \`main\`
          *Commit:* [${GITHUB_SHA}](${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/commit/${GITHUB_SHA})
          *Autor:* ${GITHUB_ACTOR}
          *Ambiente:* Produção
          Verifique os logs do GitHub Actions.
          EOF
                    )
                    curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage \
                      -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
                      --data-urlencode text="$TEXT" \
            -d parse_mode=Markdown
